FROM almalinux:9
ENV course="DevOps with AWS"\
    tariner="siva kumar reddy"\
    duration="120hrs"
#here username is a key ,some_user is default value
ARG ${username:-some_user}
RUN echo "Hello user : ${username}"
CMD ["sleep", "100"]
