FROM almalinux:9
ENV course="DevOps with AWS"\
    tariner="siva kumar reddy"\
    duration="120hrs"
#here username is a key ,some_user is default value
ARG USERNAME=pradeep
RUN echo "Hello user : ${USERNAME}"
CMD ["sleep", "100"]
